name: firebase_database_rest
description: A platform independent Dart/Flutter wrapper for the Firebase
  Realtime Database API based on REST.
version: 1.0.2
homepage: https://github.com/Skycoder42/firebase_database_rest

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth_rest: ^2.0.0
  freezed_annotation: ^0.14.0
  http: ^0.13.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^1.11.5 # X
  coverage: ^1.0.1
  dart_pre_commit: ^2.2.0-nullsafety.2
  freezed: ^0.14.0+1
  json_serializable: ^4.0.2
  lint: ^1.5.3
  mockito: ^5.0.0
  test: ^1.16.5
  test_api: ^0.2.19
  tuple: ^2.0.0-nullsafety.0
