name: firebase_database_rest
description: A platform independent Dart/Flutter wrapper for the Firebase
  Realtime Database API based on REST.
version: 0.1.0
homepage: https://github.com/Skycoder42/firebase_database_rest

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: ^0.12.2
  json_annotation: ^3.1.0
  freezed_annotation: ^0.12.0
  logging: ^0.11.4
  firebase_auth_rest: ^1.0.0
  path: ^1.7.0

dev_dependencies:
  test: ^1.15.3
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  freezed: ^0.12.2
  lint: ^1.3.0
  mockito: ^4.1.3
  cider: ^0.0.5
  dart_pre_commit: ^1.1.1
  coverage: ^0.14.1
  hanzo: ^1.0.2
